### ISSUE TITLE
VR: Self Localization Task Bug

### ISSUE THREAD

**Issue by eidueidu** [origami-team/geogami-virtual-environment#41]
VR World Game "Location Marker Pre Test" Task 4:

Task 4 is a "self localization task" where you need to tap on the map for your own location. Unlinke in task 1, in task 4 the red dot disappears after a few seconds (5 or 10 sec), even if I don't tap on the map. Same for task 20.

**Comment by YouQam** [comment]
@eidueidu  This is due to setting in task 'marker settings' -> you can change `Location marker` value to `off` to keep the red dot.

![Image](https://github.com/origami-team/geogami-virtual-environment/assets/40634685/d2c011a3-3d90-4fe8-b203-7ee22f39c55d)
